replicaCount: 1

image:
  repository: hareesh52/githubactionsdemo
  tag: latest
  pullPolicy: Always

service:
  type: NodePort
  port: 8080
  targetPort: 8080

ingress:
  enabled: false

resources: {}